name: Formatting, lints, and code checks
on: [push, pull_request]

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install components
        uses: dtolnay/rust-toolchain@master
        with:
          components: clippy, rustfmt
          toolchain: nightly
      - name: Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: thumbv8m.main-none-eabi
      - name: Check formatting
        run: cargo +nightly fmt --all -- --check
      - name: Install linter
        run: cargo install cargo-lints
      - name: Run linter
        run: cargo +stable lints clippy --all-targets --all-features
      - name: Check code
        run: cargo +stable check --release --all-targets
      - name: Check code (no default features)
        run: cargo +stable check --release --no-default-features
      # This check here is to ensure that it builds for no-std rust targets
      - name: Check code (no-std)
        run: cargo +stable check --no-default-features --target=thumbv8m.main-none-eabi
      - name: Check benchmarks
        run: cargo +stable check --benches
